repository: sudweb/estcequecestbientot
url: https://estcequecestbientot.sudweb.fr
title: Est-ce que c'est bientôt Sud Web ?
description:
logo: /assets/images/logo.png
twitter:
  username: sudweb

google:
  tracking_id: UA-22076213-3

sass:
    style: compressed

exclude:
  - .editorconfig
  - .gitignore
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - script
  - vendor

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
